packages:
  - examples/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  workerd: true

overrides:
  vite-dev-rpc: ^2.0.0
  vite-plugin-inspect: ^11.4.1

minimumReleaseAgeExclude:
  - '@nuxt/kit@4.4.8'
  - '@nuxt/nitro-server@4.4.8'
  - '@nuxt/schema@4.4.8'
  - '@nuxt/vite-builder@4.4.8'
  - nuxt@4.4.8
